### ISSUE TITLE
Improving `read_line` output

### ISSUE THREAD

**Issue by jonathandturner** [jonathandturner/reedline#18]
From the twitch chat:

"boom_rang: In my mind the "exit" keyword is a concern of the REPL, read_line could return a enum where a string is one option and then Ctrl-C and Ctrl-D can have a special return each"

**Comment by sholderbach** [comment]
Other special commands at the shell/line editor boundary would include `Ctrl+L` / `clear` which could break things for people that would want to use `reedline` in an other than shell REPL context like single command entry but are probably among the things people expect to work in a shell

**Comment by jonathandturner** [comment]
@sholderbach would you mind filling an issue for clear? I'm going to close this issue as the original point about needing a way of mapping signals has been fixed

**Comment by jonathandturner** [comment]
Closing this as fixed in #22
