### ISSUE TITLE
Clear screen/Ctrl+L/Form Feed

### ISSUE THREAD

**Issue by sholderbach** [jonathandturner/reedline#28]
To emulate the behavior in bash/zsh etc. :

Maybe we consider a separation of concerns between core line editor and typical interactive shell terminal to make screen clearing optional for non shell/REPL usecases e.g. single command entry like vi `:`

On the side of the line editor `Engine`:
* Respond to `Ctrl+L`
* Keep current line_buffer state (including cursor position/`insertion_point`)

Helper to provide the functionality (MVP: call this in main):
* Print a screen worth of newlines (At least thats the behavior of 
FormFeed under gnome-terminal)
* Scroll new prompt to first line and repaint including cursor position

**Comment by jonathandturner** [comment]
Fixed with #30
